// Package main is a developer tool to copy and verify generated Go protobuf files
// in the workspace source tree.
//
// Invocation:
// This program is typically not invoked directly. Instead, it is executed via targets
// generated by the `write_go_proto_sources` macro:
//   1. bazel run //:update_protos (sync mode)
//   2. bazel test //:update_protos_test (check mode)
//
// Tricky Bits & Design Decisions:
//
// 1. No CLI Flags / Environment Variables for Configuration:
//    Bazel's `DefaultInfo` provider allows returning an executable target for rules,
//    but it does not support defining default command line arguments (e.g., flags)
//    to pass when running that target. To avoid writing shell wrapper scripts (which
//    can be brittle and non-cross-platform), the Starlark rules propagate the path
//    of the generated JSON configuration file to this tool using `RunEnvironmentInfo`
//    via the `CONFIG_JSON_PATH` environment variable.
//
// 2. Runfiles & Path Resolution:
//    Because Bazel builds are hermetic and run in sandboxed environments, absolute paths
//    to the workspace or execution directories are unknown at build (Starlark) time.
//    Therefore, this tool relies on the official Bazel Go runfiles library to dynamically
//    locate generated files and its own JSON configuration at runtime.
//
// 3. Workspace Drift Detection:
//    When running in test ('check') mode, the tool runs inside Bazel's sandbox. The sandbox
//    contains symlinks to workspace files. To verify drift against the host's real source
//    tree files, the tool locates the sandboxed `MODULE.bazel` runfile, follows its symlink
//    to the real source tree file using `filepath.EvalSymlinks`, and uses that parent
//    directory as the source of truth workspace root.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/bazelbuild/rules_go/go/runfiles"
)

type FileMapping struct {
	Src  string `json:"src"`  // Path relative to runfiles
	Dest string `json:"dest"` // Path relative to workspace root
}

type Config struct {
	Mode  string        `json:"mode"` // "sync" or "check"
	Files []FileMapping `json:"files"`
}

func main() {
	configRunfilePath := os.Getenv("CONFIG_JSON_PATH")
	if configRunfilePath == "" {
		execName := filepath.Base(os.Args[0])
		configRunfilePath = fmt.Sprintf("_main/%s.json", execName)
	}

	rpath, err := runfiles.Rlocation(configRunfilePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to locate configuration runfile %s: %v\n", configRunfilePath, err)
		os.Exit(1)
	}

	configBytes, err := os.ReadFile(rpath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read configuration: %v\n", err)
		os.Exit(1)
	}

	var config Config
	if err := json.Unmarshal(configBytes, &config); err != nil {
		fmt.Fprintf(os.Stderr, "invalid configuration format: %v\n", err)
		os.Exit(1)
	}

	if config.Mode == "sync" {
		err = runSync(config.Files)
	} else {
		err = runCheck(config.Files)
	}

	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
}

func runSync(files []FileMapping) error {
	workspaceDir := os.Getenv("BUILD_WORKSPACE_DIRECTORY")
	if workspaceDir == "" {
		return fmt.Errorf("BUILD_WORKSPACE_DIRECTORY is not set; must run via 'bazel run'")
	}

	for _, fm := range files {
		srcPath, err := runfiles.Rlocation(fm.Src)
		if err != nil {
			return fmt.Errorf("failed to locate runfile %s: %w", fm.Src, err)
		}
		destPath := filepath.Join(workspaceDir, fm.Dest)

		if err := os.MkdirAll(filepath.Dir(destPath), 0755); err != nil {
			return fmt.Errorf("failed to create directory for %s: %w", fm.Dest, err)
		}

		if err := copyFile(srcPath, destPath); err != nil {
			return fmt.Errorf("failed to copy %s to %s: %w", fm.Src, fm.Dest, err)
		}
		
		// Ensure the file is writable.
		if err := os.Chmod(destPath, 0644); err != nil {
			return fmt.Errorf("failed to set write permissions on %s: %w", fm.Dest, err)
		}
		fmt.Printf("Updated: %s\n", fm.Dest)
	}
	return nil
}

func runCheck(files []FileMapping) error {
	workspaceRoot, err := findWorkspaceRoot()
	if err != nil {
		return fmt.Errorf("failed to detect workspace root: %w", err)
	}

	failed := false
	for _, fm := range files {
		srcPath, err := runfiles.Rlocation(fm.Src)
		if err != nil {
			return fmt.Errorf("failed to locate runfile %s: %w", fm.Src, err)
		}
		destPath := filepath.Join(workspaceRoot, fm.Dest)

		if _, err := os.Stat(destPath); os.IsNotExist(err) {
			fmt.Fprintf(os.Stderr, "source file does not exist in workspace: %s\n", fm.Dest)
			failed = true
			continue
		}

		match, err := filesAreEqual(srcPath, destPath)
		if err != nil {
			return err
		}
		if !match {
			fmt.Fprintf(os.Stderr, "source file out of sync: %s\n", fm.Dest)
			failed = true
		}
	}

	if failed {
		return fmt.Errorf("verification failed; run the update target to sync generated files")
	}
	fmt.Println("All generated Go proto files are up to date!")
	return nil
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, in)
	return err
}

func filesAreEqual(path1, path2 string) (bool, error) {
	f1, err := os.ReadFile(path1)
	if err != nil {
		return false, err
	}
	f2, err := os.ReadFile(path2)
	if err != nil {
		return false, err
	}
	return bytes.Equal(f1, f2), nil
}

func findWorkspaceRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		marker := filepath.Join(dir, "MODULE.bazel")
		if _, err := os.Stat(marker); err == nil {
			realPath, err := filepath.EvalSymlinks(marker)
			if err != nil {
				return "", err
			}
			return filepath.Dir(realPath), nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	return "", fmt.Errorf("could not find MODULE.bazel in any parent directory")
}
