// Package main is a developer tool to copy and verify generated Go protobuf files
// in the workspace source tree.
//
// Invocation:
// This program is typically not invoked directly. Instead, it is executed via targets
// generated by the `write_go_proto_srcs` macro:
//   1. bazel run //:update_protos (sync mode)
//   2. bazel test //:update_protos_test (check mode)
//
// Tricky Bits & Design Decisions:
//
// 1. No CLI Flags / Environment Variables for Configuration:
//    Bazel's `DefaultInfo` provider allows returning an executable target for rules,
//    but it does not support defining default command line arguments (e.g., flags)
//    to pass when running that target. To avoid writing shell wrapper scripts (which
//    can be brittle and non-cross-platform), the Starlark rules propagate the path
//    of the generated JSON configuration file to this tool using `RunEnvironmentInfo`
//    via the `CONFIG_JSON_PATH` environment variable.
//
// 2. Runfiles & Path Resolution:
//    Because Bazel builds are hermetic and run in sandboxed environments, absolute paths
//    to the workspace or execution directories are unknown at build (Starlark) time.
//    Therefore, this tool relies on the official Bazel Go runfiles library to dynamically
//    locate generated files and its own JSON configuration at runtime.
//
// 3. Workspace Drift Detection:
//    When running in test ('check') mode, the tool runs entirely inside Bazel's hermetic
//    sandbox. By declaring both the generated `.pb.go` files and the checked-in `.pb.go`
//    files as test runfiles, Bazel mounts both inside the sandbox. The tool then resolves
//    both paths using the Go runfiles library (`runfiles.Rlocation`) and compares them
//    directly. This eliminates any need to traverse the host filesystem or follow
//    external workspace symlinks.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/bazelbuild/rules_go/go/runfiles"
)

type FileMapping struct {
	Src  string `json:"src"`  // Path relative to runfiles
	Dest string `json:"dest"` // Path relative to workspace root
}

type Config struct {
	Mode                  string        `json:"mode"` // "sync" or "check"
	Verbosity             string        `json:"verbosity"`
	SuggestedUpdateTarget string        `json:"suggested_update_target"`
	Files                 []FileMapping `json:"files"`
}

func main() {
	configRunfilePath := os.Getenv("CONFIG_JSON_PATH")
	var configBytes []byte
	var err error

	if configRunfilePath != "" {
		var rpath string
		rpath, err = runfiles.Rlocation(configRunfilePath)
		if err == nil {
			configBytes, err = os.ReadFile(rpath)
		}
	} else {
		// Fallback 1: Try reading next to the executable path
		var exePath string
		exePath, err = os.Executable()
		if err == nil {
			configBytes, err = os.ReadFile(exePath + ".json")
			if err != nil {
				configBytes, err = os.ReadFile(filepath.Join(filepath.Dir(exePath), getBaseName(exePath)+".json"))
			}
		}

		// Fallback 2: Try reading next to os.Args[0]
		if err != nil {
			configBytes, err = os.ReadFile(os.Args[0] + ".json")
			if err != nil {
				configBytes, err = os.ReadFile(filepath.Join(filepath.Dir(os.Args[0]), getBaseName(os.Args[0])+".json"))
			}
		}

		// Fallback 3: Hardcoded main package path relative to runfiles
		if err != nil {
			var rpath string
			rpath, err = runfiles.Rlocation(fmt.Sprintf("_main/%s.json", getBaseName(os.Args[0])))
			if err == nil {
				configBytes, err = os.ReadFile(rpath)
			}
		}
	}

	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read configuration JSON: %v\n", err)
		os.Exit(1)
	}

	var config Config
	if err := json.Unmarshal(configBytes, &config); err != nil {
		fmt.Fprintf(os.Stderr, "invalid configuration format: %v\n", err)
		os.Exit(1)
	}

	// Automatically run in check mode if executed under Bazel test environment.
	isTest := os.Getenv("TEST_WORKSPACE") != "" || os.Getenv("TEST_SRCDIR") != ""
	if isTest || config.Mode == "check" {
		err = runCheck(config)
	} else {
		err = runSync(config)
	}

	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
}

func runSync(config Config) error {
	workspaceDir := os.Getenv("BUILD_WORKSPACE_DIRECTORY")
	if workspaceDir == "" {
		return fmt.Errorf("BUILD_WORKSPACE_DIRECTORY is not set; must run via 'bazel run'")
	}

	for _, fm := range config.Files {
		srcPath, err := runfiles.Rlocation(fm.Src)
		if err != nil {
			return fmt.Errorf("failed to locate runfile %s: %w", fm.Src, err)
		}
		destPath := filepath.Join(workspaceDir, fm.Dest)

		if err := os.MkdirAll(filepath.Dir(destPath), 0755); err != nil {
			return fmt.Errorf("failed to create directory for %s: %w", fm.Dest, err)
		}

		if err := copyFile(srcPath, destPath); err != nil {
			return fmt.Errorf("failed to copy %s to %s: %w", fm.Src, fm.Dest, err)
		}

		// Ensure the file is writable.
		if err := os.Chmod(destPath, 0644); err != nil {
			return fmt.Errorf("failed to set write permissions on %s: %w", fm.Dest, err)
		}

		if config.Verbosity == "full" || config.Verbosity == "" {
			fmt.Printf("Updated: %s\n", fm.Dest)
		}
	}

	if config.Verbosity == "short" {
		fmt.Printf("Synchronized %d Go protobuf files.\n", len(config.Files))
	}
	return nil
}

func runCheck(config Config) error {
	failed := false
	testWorkspace := os.Getenv("TEST_WORKSPACE")
	if testWorkspace == "" {
		testWorkspace = "_main"
	}

	for _, fm := range config.Files {
		srcPath, err := runfiles.Rlocation(fm.Src)
		if err != nil {
			return fmt.Errorf("failed to locate generated runfile %s: %w", fm.Src, err)
		}

		destRunfilePath := testWorkspace + "/" + fm.Dest
		destPath, err := runfiles.Rlocation(destRunfilePath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "source file does not exist in workspace: %s\n", fm.Dest)
			failed = true
			continue
		}

		if _, err := os.Stat(destPath); os.IsNotExist(err) {
			fmt.Fprintf(os.Stderr, "source file does not exist in workspace: %s\n", fm.Dest)
			failed = true
			continue
		}

		match, err := filesAreEqual(srcPath, destPath)
		if err != nil {
			return err
		}
		if !match {
			fmt.Fprintf(os.Stderr, "source file out of sync: %s\n", fm.Dest)
			failed = true
		}
	}

	if failed {
		suggestedCmd := getSuggestedCommand(config)
		return fmt.Errorf("verification failed; to sync generated files, run:\n    %s", suggestedCmd)
	}
	if config.Verbosity == "full" || config.Verbosity == "short" || config.Verbosity == "" {
		fmt.Println("All generated Go proto files are up to date!")
	}
	return nil
}

func getSuggestedCommand(config Config) string {
	if config.SuggestedUpdateTarget != "" {
		return fmt.Sprintf("bazel run %s", config.SuggestedUpdateTarget)
	}
	testTarget := os.Getenv("TEST_TARGET")
	if testTarget != "" {
		if len(testTarget) > 5 && testTarget[len(testTarget)-5:] == "_test" {
			return fmt.Sprintf("bazel run %s", testTarget[:len(testTarget)-5])
		}
		return fmt.Sprintf("bazel run %s", testTarget)
	}
	return "bazel run :<your_update_target>"
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, in)
	return err
}

func filesAreEqual(path1, path2 string) (bool, error) {
	f1, err := os.ReadFile(path1)
	if err != nil {
		return false, err
	}
	f2, err := os.ReadFile(path2)
	if err != nil {
		return false, err
	}
	return bytes.Equal(f1, f2), nil
}

func getBaseName(path string) string {
	base := filepath.Base(path)
	for {
		ext := filepath.Ext(base)
		if ext == "" {
			break
		}
		base = base[:len(base)-len(ext)]
	}
	if len(base) > 5 && base[len(base)-5:] == "_test" {
		base = base[:len(base)-5]
	}
	return base
}
